
service: capstone-chat-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  websocketsApiName: capstone-websocket-api
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  
  connectHandler:
    handler: src/lambda/socketHandler.connectHandler
    events:
      - websocket: $connect
      
  
  disconnectHandler:
    handler: src/lambda/socketHandler.disconnectHandler
    events:
      - websocket: $disconnect

  defaultHandler:
    handler: src/lambda/socketHandler.defaultHandler
    events:
      - websocket: $default
