
service: capstone-chat-backend

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

frameworkVersion: '2'



provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  websocketsApiName: capstone-websocket-api
  websocketsApiRouteSelectionExpression: $request.body.action

  environment:
    SESSIONS_TABLE: SESSIONS_TABLE
    SESSIONS_INDEX: SESSIONS_INDEX
    USERS_TABLE: USERS_TABLE2
    MESSAGES_TABLE: MESSAGES_TABLE
    ICON_BUCKET: fedor-uda-icon-bucket
    URL_EXPIRE: URL_EXPIRE
  

functions:

  Auth: 
    handler: src/lambda/authorizer.handler
  
  connectHandler:
    handler: src/lambda/socketHandler.connectHandler
    events:
      - websocket:
          route: $connect
          authorizer: 
            name: Auth
            identitySource:
              - 'route.request.querystring.Auth'
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SESSIONS_TABLE}
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}
  
  disconnectHandler:
    handler: src/lambda/socketHandler.disconnectHandler
    events:
      - websocket: $disconnect
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SESSIONS_TABLE}

  defaultHandler:
    handler: src/lambda/socketHandler.defaultHandler
    events:
      - websocket: $default

  getProfileInfo:
    handler: src/lambda/getProfileInfo.handler
    events:
      - websocket: getProfileInfo
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: arn:aws:execute-api:${self:provider.region}:*:*

  updateProfileInfo:
    handler: src/lambda/updateProfileInfo.handler
    events:
      - websocket: updateProfileInfo
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: arn:aws:execute-api:${self:provider.region}:*:*

  getUploadUrl:
    handler: src/lambda/getUploadUrl.handler
    events:
      - websocket: getUploadUrl
    iamRoleStatements:    
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: arn:aws:execute-api:${self:provider.region}:*:*
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::${self:provider.environment.ICON_BUCKET}/*

  processMessage:
    handler: src/lambda/processMessage.handler
    events:
      - websocket: sendMessage
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MESSAGES_TABLE}
    - Effect: Allow
      Action:
        - dynamodb:Scan        
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SESSIONS_TABLE}
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: arn:aws:execute-api:${self:provider.region}:*:*

  getCurrentMessages:
    handler: src/lambda/getCurrentMessages.handler
    events:
      - websocket: getMessages
    iamRoleStatements:
    - Effect: Allow
      Action:        
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MESSAGES_TABLE}    
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: arn:aws:execute-api:${self:provider.region}:*:*
    


resources:

  Resources:

    # Table to keep track of the websocket connections
    SessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: princId
            AttributeType: S          
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: loggedIn
            AttributeType: S          
        KeySchema:
          - AttributeName: princId
            KeyType: HASH
          - AttributeName: connectionId
            KeyType: RANGE          
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.SESSIONS_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.SESSIONS_INDEX}
            KeySchema:
              - AttributeName: princId
                KeyType: HASH
              - AttributeName: loggedIn
                KeyType: RANGE
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index

    # Table to keep track of the user profiles (kept persistently between sessions)
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: princId
            AttributeType: S                    
        KeySchema:
          - AttributeName: princId
            KeyType: HASH          
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.USERS_TABLE}

    # Table to store the chat messages
    MessageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: postDay
            AttributeType: S
          - AttributeName: postDate
            AttributeType: S                    
        KeySchema:
          - AttributeName: postDay
            KeyType: HASH
          - AttributeName: postDate
            KeyType: RANGE          
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.MESSAGES_TABLE}

    # The s3 bucket for the profile pictures
    IconBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ICON_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.ICON_BUCKET}/*'
        Bucket: !Ref IconBucket














  
        
